repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13 # Use the latest ruff release
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Automatically fix issues and exit with non-zero if fixes were applied
      - id: ruff-format # Add ruff-format for auto-formatting 