repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.16.0
  #   hooks:
  #     - id: mypy
  #       args: [--exclude, config/settings/__init__.py, --explicit-package-bases]
  #       additional_dependencies:
  #         - types-requests
  #         - types-PyYAML
  #         - types-python-dateutil
  #         - types-setuptools
  #         - django-stubs
  #         - djangorestframework-stubs
  #         - python-dotenv
  #         - cloudinary
  #         - djangorestframework
  #         - djangorestframework-simplejwt
  #         - django-storages
  #         - django-cors-headers
  #         - drf-yasg
  #         - pillow
  #         - requests
  #         - django-cloudinary-storage
  #         - charset-normalizer
  #         - reportlab
  #         - certifi
  #         - psycopg2-binary
  #         - django-filter

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, html, yaml]
        additional_dependencies:
          - prettier@4.0.0-alpha.8
