services:
  db:
    container_name: wistar_db
    image: postgres:16
    restart: always
    volumes:
      - local_db:/var/lib/postgresql/data
    env_file:
#      확장자 관계 없이 환경 파일을 읽음.
#      KEY=VALUE 형식만 지키면 됨
#      반드시 docker postgres가 사용 가능한 key이름을 사용. 공백 x
#      - ../../envs/test.txt
      - ../../envs/.env
    environment:
#      docker-compose.yml 파일과 같은 디렉토리에 위치에 .env파일이 있는 경우 사용 가능
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/wistar_db/
    ports:
      - "54330:5432"

volumes:
  local_db: