# Generated by Django 5.2.3 on 2025-06-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "000X_remove_social_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "관리자"), ("manager", "매니저"), ("user", "일반회원")],
                default="user",
                max_length=20,
                verbose_name="역할",
            ),
        ),
    ]
