# Generated by Django 5.2 on 2025-05-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=50, unique=True, verbose_name="이메일"
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="이름")),
                (
                    "nickname",
                    models.CharField(max_length=25, unique=True, verbose_name="닉네임"),
                ),
                (
                    "last_login",
                    models.DateTimeField(null=True, verbose_name="마지막 로그인"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="스태프 권한"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="관리자 권한"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="계정 활성화"),
                ),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저 목록",
                "db_table": "user",
            },
        ),
    ]
