# Generated by Django 5.2 on 2025-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, verbose_name="이메일 인증 토큰"),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0, verbose_name="실패한 로그인 시도 횟수"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="이메일 인증 여부"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_failed_login_attempt",
            field=models.DateTimeField(blank=True, null=True, verbose_name="마지막 실패한 로그인 시도 시간"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="휴대폰"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="프로필 이미지",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="소셜 ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="social_type",
            field=models.CharField(blank=True, max_length=20, verbose_name="소셜 타입"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_grade",
            field=models.CharField(
                choices=[
                    ("BRONZE", "브론즈"),
                    ("SILVER", "실버"),
                    ("GOLD", "골드"),
                    ("PLATINUM", "플래티넘"),
                ],
                default="BRONZE",
                max_length=20,
                verbose_name="회원 등급",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "관리자"),
                    ("NORMAL", "일반회원"),
                    ("BLACKLIST", "블랙리스트"),
                ],
                default="NORMAL",
                max_length=20,
                verbose_name="회원 유형",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
    ]
