# Generated by Django 5.2.3 on 2025-06-18 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="채팅방 이름")),
                ("description", models.TextField(blank=True, null=True, verbose_name="채팅방 설명")),
                ("max_participants", models.PositiveIntegerField(default=10, verbose_name="최대 참여자 수")),
                (
                    "room_type",
                    models.CharField(
                        choices=[("DIRECT", "1:1 채팅"), ("GROUP", "그룹 채팅")],
                        default="DIRECT",
                        max_length=20,
                        verbose_name="채팅방 유형",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("last_message_at", models.DateTimeField(blank=True, null=True, verbose_name="마지막 메시지 시간")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("participants", models.ManyToManyField(related_name="chat_rooms", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "채팅방",
                "verbose_name_plural": "채팅방들",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoomParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자 여부")),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="참여일")),
                ("left_at", models.DateTimeField(blank=True, null=True, verbose_name="퇴장일")),
                ("last_read_at", models.DateTimeField(blank=True, null=True, verbose_name="마지막 읽은 시간")),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_participants",
                        to="chat_room.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅방 참여자",
                "verbose_name_plural": "채팅방 참여자들",
                "unique_together": {("chat_room", "user")},
            },
        ),
    ]
