# Generated by Django 5.2.3 on 2025-06-18 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("PROCESSING", "처리중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                            ("REFUNDED", "환불"),
                        ],
                        max_length=20,
                        verbose_name="이전 상태",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("PROCESSING", "처리중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                            ("REFUNDED", "환불"),
                        ],
                        max_length=20,
                        verbose_name="새 상태",
                    ),
                ),
                ("reason", models.TextField(verbose_name="변경 사유")),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="변경자",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="order.order",
                        verbose_name="주문",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문 상태 로그",
                "verbose_name_plural": "주문 상태 로그",
                "ordering": ["-created_at"],
            },
        ),
    ]
