# Generated by Django 5.2 on 2025-05-15 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Idol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("en_name", models.CharField(blank=True, max_length=255)),
                ("debut_date", models.DateField(blank=True, null=True)),
                ("agency", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True)),
                ("profile_image", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_idols",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "아이돌",
                "verbose_name_plural": "아이돌들",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="idol_idol_name_e2162c_idx"),
                    models.Index(fields=["agency"], name="idol_idol_agency_e178e1_idx"),
                    models.Index(
                        fields=["debut_date"], name="idol_idol_debut_d_584779_idx"
                    ),
                ],
            },
        ),
    ]
